/* AUTO-GENERATED bởi scripts/build-icons.mjs — ĐỪNG sửa tay.
   Bộ icon của dự án: mỗi component render bằng Material Symbols (qua <Ic>).
   Tên component theo quy ước lucide cũ để không phải sửa JSX toàn repo.
   Import: `import { Home, Search } from "@/components/icons"`. */
import { Ic } from "@/components/icon";
import type { ComponentProps, ReactElement } from "react";

export type LucideProps = Omit<ComponentProps<typeof Ic>, "icon"> & {
  size?: number | string;
  strokeWidth?: number | string;
  absoluteStrokeWidth?: boolean;
};
export type LucideIcon = (props: LucideProps) => ReactElement;

function make(name: string): LucideIcon {
  return function LucideShimIcon({ size, absoluteStrokeWidth, ...props }: LucideProps) {
    void absoluteStrokeWidth;
    const dim = size != null ? { width: size, height: size } : {};
    return <Ic icon={name} {...dim} {...props} />;
  };
}

export const AlertCircle = make("alert-circle");
export const AlignCenter = make("align-center");
export const AlignLeft = make("align-left");
export const AlignRight = make("align-right");
export const ArrowDownWideNarrow = make("arrow-down-wide-narrow");
export const ArrowLeft = make("arrow-left");
export const ArrowRight = make("arrow-right");
export const ArrowUp = make("arrow-up");
export const ArrowUpRight = make("arrow-up-right");
export const BadgeCheck = make("badge-check");
export const BedDouble = make("bed-double");
export const Bell = make("bell");
export const Bike = make("bike");
export const Bold = make("bold");
export const BookOpen = make("book-open");
export const Building2 = make("building-2");
export const Bus = make("bus");
export const CalendarClock = make("calendar-clock");
export const CalendarDays = make("calendar-days");
export const Camera = make("camera");
export const Car = make("car");
export const CarTaxiFront = make("car-taxi-front");
export const Check = make("check");
export const CheckCheck = make("check-check");
export const CheckCircle2 = make("check-circle-2");
export const CheckIcon = make("check");
export const ChefHat = make("chef-hat");
export const ChevronDown = make("chevron-down");
export const ChevronDownIcon = make("chevron-down");
export const ChevronLeft = make("chevron-left");
export const ChevronLeftIcon = make("chevron-left");
export const ChevronRight = make("chevron-right");
export const ChevronRightIcon = make("chevron-right");
export const ChevronUp = make("chevron-up");
export const ChevronUpIcon = make("chevron-up");
export const ChevronsUpDown = make("chevrons-up-down");
export const CircleCheck = make("circle-check");
export const CircleIcon = make("circle");
export const Clock = make("clock");
export const Cloud = make("cloud");
export const Compass = make("compass");
export const ConciergeBell = make("concierge-bell");
export const Construction = make("construction");
export const Crosshair = make("crosshair");
export const Database = make("database");
export const DatabaseZap = make("database-zap");
export const Download = make("download");
export const ExternalLink = make("external-link");
export const Eye = make("eye");
export const EyeOff = make("eye-off");
export const FileText = make("file-text");
export const Flag = make("flag");
export const Footprints = make("footprints");
export const Frown = make("frown");
export const Globe = make("globe");
export const Heading2 = make("heading-2");
export const Heading3 = make("heading-3");
export const Heart = make("heart");
export const HelpCircle = make("help-circle");
export const Home = make("home");
export const Image = make("image");
export const ImageIcon = make("image");
export const ImageOff = make("image-off");
export const ImagePlus = make("image-plus");
export const Info = make("info");
export const Italic = make("italic");
export const KeyRound = make("key-round");
export const Landmark = make("landmark");
export const Layers = make("layers");
export const LayoutDashboard = make("layout-dashboard");
export const LayoutGrid = make("layout-grid");
export const Lightbulb = make("lightbulb");
export const Link2 = make("link-2");
export const List = make("list");
export const ListOrdered = make("list-ordered");
export const Loader2 = make("loader-2");
export const Lock = make("lock");
export const LockOpen = make("lock-open");
export const LogOut = make("log-out");
export const Mail = make("mail");
export const Map = make("map");
export const MapPin = make("map-pin");
export const MapPinCheck = make("map-pin-check");
export const MapPinCheckInside = make("map-pin-check-inside");
export const MapPinPlus = make("map-pin-plus");
export const MapPinned = make("map-pinned");
export const Maximize = make("maximize");
export const Meh = make("meh");
export const Menu = make("menu");
export const MessageCircle = make("message-circle");
export const MessageSquare = make("message-square");
export const MessageSquareText = make("message-square-text");
export const MessagesSquare = make("messages-square");
export const MoreHorizontal = make("more-horizontal");
export const MoreHorizontalIcon = make("more-horizontal");
export const Mountain = make("mountain");
export const Navigation = make("navigation");
export const Newspaper = make("newspaper");
export const PanelLeftIcon = make("panel-left");
export const Pause = make("pause");
export const PenLine = make("pen-line");
export const Pencil = make("pencil");
export const Phone = make("phone");
export const Pin = make("pin");
export const PinOff = make("pin-off");
export const Plane = make("plane");
export const PlaneLanding = make("plane-landing");
export const Play = make("play");
export const Plus = make("plus");
export const Quote = make("quote");
export const Redo2 = make("redo-2");
export const RefreshCw = make("refresh-cw");
export const Reply = make("reply");
export const RotateCcw = make("rotate-ccw");
export const RotateCw = make("rotate-cw");
export const Route = make("route");
export const Search = make("search");
export const SearchIcon = make("search");
export const Send = make("send");
export const Settings = make("settings");
export const Share2 = make("share-2");
export const Shield = make("shield");
export const ShieldAlert = make("shield-alert");
export const ShieldCheck = make("shield-check");
export const ShieldQuestion = make("shield-question");
export const ShieldX = make("shield-x");
export const Ship = make("ship");
export const Sliders = make("sliders");
export const Smile = make("smile");
export const Sparkles = make("sparkles");
export const Star = make("star");
export const Store = make("store");
export const Strikethrough = make("strikethrough");
export const Tag = make("tag");
export const ThumbsUp = make("thumbs-up");
export const Ticket = make("ticket");
export const TrainFront = make("train-front");
export const Trash2 = make("trash-2");
export const TriangleAlert = make("triangle-alert");
export const Underline = make("underline");
export const Undo2 = make("undo-2");
export const UploadCloud = make("upload-cloud");
export const User = make("user");
export const UserPlus = make("user-plus");
export const Users = make("users");
export const Utensils = make("utensils");
export const UtensilsCrossed = make("utensils-crossed");
export const Wallet = make("wallet");
export const X = make("x");
export const XCircle = make("x-circle");
export const XIcon = make("x");
